/**
 * Wire types for the Surveillance Video Query API, as documented at
 * https://surveillance-backend-nodd.onrender.com/docs (OpenAPI schema).
 * These mirror the backend's raw response shapes — `normalize.ts` converts
 * them into the app's own `Clip`/`RecentQuery`/etc. domain types.
 */

export interface RagResultItem {
  video_id: string;
  video_url: string | null;
  start_seconds: number;
  end_seconds: number;
  caption: string;
  score: number;
  /** Enriched by the backend from bronze.events / bronze.videos (spec §4.1). */
  event_id?: string | null;
  event_name?: string | null;
  description?: string | null;
  camera?: string | null;
  scene?: string | null;
  thumbnail_url?: string | null;
  tags?: string[] | null;
  /** Requested (spec §2): the number `answer` cites this result by, as in `[2]`. Kept
   *  when other results are dropped, so citations never shift. */
  citation_index?: number | null;
  /** The video's start in the camera's local time, with no offset (`2018-03-05T13:15:00`):
   *  its time zone is unknown. Null only when bronze has no start. */
  capture_start_local?: string | null;
}

export interface RagQueryResult {
  answer: string;
  results: RagResultItem[];
}

export interface ApiClip {
  id: string;
  camera: string;
  code: string;
  ts: string;
  date: string;
  order: number;
  confidence: number;
  tags: string[];
  objects: string;
  action: string;
  thumbnailUrl: string | null;
  videoUrl: string | null;
  /** Requested (§4.1): `bronze.videos.scene`. */
  scene?: string | null;
  /** Requested: the event's bounds in seconds into `videoUrl`, so Clip Detail can
   *  open the footage at the moment instead of at 0:00. */
  startSeconds?: number | null;
  endSeconds?: number | null;
  /** As `RagResultItem.capture_start_local`. */
  captureStartLocal?: string | null;
}

export interface ApiCameraDirectoryEntry {
  code: string;
  eventCount: number;
  /** Requested: `bronze.videos.scene`, to group the directory by site. */
  scene?: string | null;
}

export interface ApiRecentQuery {
  id: string;
  text: string;
  ts: string;
  cameras: number;
}

export interface ApiSavedQuery {
  id: string;
  text: string;
  savedOn: string;
  hits: number;
}

/*
 * ---------------------------------------------------------------------------
 * `POST /api/v1/assistant/ask` — the RAG answers a follow-up question about the
 * search results or one moment. The backend is stateless: every request carries
 * the query, the moments and the thread so far.
 * ---------------------------------------------------------------------------
 */

/**
 * One matched moment, exactly as the frontend holds it. The request carries the
 * moments on screen so the endpoint can stay stateless (no stored search to look
 * up); the alternative is a `search_id` returned by `/search`, which keeps the
 * payload small but makes the backend persist every result set.
 */
export interface AssistantMoment {
  /** The frontend's id for the moment — the response cites moments by it. */
  moment_id: string;
  video_id: string;
  start_seconds: number;
  end_seconds: number | null;
  caption: string;
  /** 0–1, as `/search` returned it. */
  score: number;
  /** `null` while the RAG doesn't return cameras (see the /search gaps). */
  camera: string | null;
  /** bronze.events.event_id, so the backend can read the event's real detections for
   *  its suggestions; `null` falls back to the caption. Ignored by older backends. */
  event_id?: string | null;
}

export interface AssistantAskRequest {
  /** The search that produced the moments. */
  query: string;
  question: string;
  /** "results": about all moments on screen. "moment": about `focus_moment_id`. */
  scope: "results" | "moment";
  focus_moment_id: string | null;
  moments: AssistantMoment[];
  /** Earlier turns of this thread, oldest first, for follow-up questions. */
  history: { role: "user" | "assistant"; text: string }[];
}

/**
 * `POST /api/v1/assistant/suggestions`: the questions to offer when the
 * thread opens or its context changes (after a search, when a moment is selected,
 * on Clip Detail), generated by the RAG from the same context as `/assistant/ask`,
 * minus the question. Follow-ups after an answer come in `AssistantAskResponse`.
 */
export type AssistantSuggestionsRequest = Omit<AssistantAskRequest, "question">;

export interface AssistantSuggestionsResponse {
  suggested_questions: string[];
}

export interface AssistantAskResponse {
  answer: string;
  /** Moments the answer is about, by `moment_id` — rendered as "jump to" buttons. */
  citations: { moment_id: string }[];
  /** Follow-ups shown under the answer. */
  suggested_questions: string[];
}

/*
 * ---------------------------------------------------------------------------
 * `GET /api/v1/videos/{video_id}/tracks` — object tracks to draw over the player.
 * Source: bronze.event_objects → bronze.objects → bronze.geometries, sized by
 * bronze.videos.frame_width/height.
 * ---------------------------------------------------------------------------
 */

/** One bounding box at one instant, in pixels of the source frame (top-left + size). */
export interface TrackBox {
  /** `geometries.timestamp_seconds` — seconds into the video. */
  t: number;
  x: number;
  y: number;
  w: number;
  h: number;
  /** `geometries.confidence`, 0–1. */
  confidence: number | null;
}

export interface ObjectTrack {
  object_id: string;
  /** `geometries.label` / `objects.label_details` — e.g. "person", "vehicle". */
  label: string;
  /** Sorted by `t`. The frontend interpolates between boxes, so ~5–10 per second is plenty. */
  boxes: TrackBox[];
}

export interface TracksResponse {
  video_id: string;
  /** `bronze.videos.frame_width` / `frame_height` — the coordinate space of every box. */
  frame_width: number;
  frame_height: number;
  objects: ObjectTrack[];
}
