/**
 * Wire types for the Surveillance Video Query API, as documented at
 * https://surveillance-backend-nodd.onrender.com/docs (OpenAPI schema).
 * These mirror the backend's raw response shapes — `normalize.ts` converts
 * them into the app's own `Clip`/`RecentQuery`/etc. domain types.
 */

export interface RagResultItem {
  video_id: string;
  video_url: string | null;
  start_seconds: number;
  end_seconds: number;
  caption: string;
  score: number;
  /** Short event label. Not in the documented contract yet — optional until the RAG confirms it. */
  event_name?: string | null;
  /** Requested (§4.1): `bronze.videos.scene`. Optional until /search returns it. */
  scene?: string | null;
}

export interface RagQueryResult {
  answer: string;
  results: RagResultItem[];
}

export interface ApiClip {
  id: string;
  camera: string;
  code: string;
  perspective: string;
  ts: string;
  date: string;
  order: number;
  confidence: number;
  tags: string[];
  objects: string;
  action: string;
  thumbnailUrl: string | null;
  videoUrl: string | null;
  /** Requested (§4.1): `bronze.videos.scene`. */
  scene?: string | null;
}

export interface ApiCameraDirectoryEntry {
  code: string;
  perspective: string;
  eventCount: number;
  /** Requested: `bronze.videos.scene`, to group the directory by site. */
  scene?: string | null;
}

export interface ApiRecentQuery {
  id: string;
  text: string;
  ts: string;
  cameras: number;
}

export interface ApiSavedQuery {
  id: string;
  text: string;
  savedOn: string;
  hits: number;
}

/*
 * ---------------------------------------------------------------------------
 * PROPOSED — `POST /api/v1/assistant/ask` (not implemented by the backend yet).
 * The frontend runs against a simulation of it (`./mocks/assistant.ts`); these
 * types are the contract the backend/RAG team is asked to implement.
 * ---------------------------------------------------------------------------
 */

/**
 * One matched moment, exactly as the frontend holds it. The request carries the
 * moments on screen so the endpoint can stay stateless (no stored search to look
 * up); the alternative is a `search_id` returned by `/search`, which keeps the
 * payload small but makes the backend persist every result set.
 */
export interface AssistantMoment {
  /** The frontend's id for the moment — the response cites moments by it. */
  moment_id: string;
  video_id: string;
  start_seconds: number;
  end_seconds: number | null;
  caption: string;
  /** 0–1, as `/search` returned it. */
  score: number;
  /** `null` while the RAG doesn't return cameras (see the /search gaps). */
  camera: string | null;
}

export interface AssistantAskRequest {
  /** The search that produced the moments. */
  query: string;
  question: string;
  /** "results": about all moments on screen. "moment": about `focus_moment_id`. */
  scope: "results" | "moment";
  focus_moment_id: string | null;
  moments: AssistantMoment[];
  /** Earlier turns of this thread, oldest first, for follow-up questions. */
  history: { role: "user" | "assistant"; text: string }[];
}

/**
 * PROPOSED `POST /api/v1/assistant/suggestions`: the questions to offer when the
 * thread opens or its context changes (after a search, when a moment is selected,
 * on Clip Detail), generated by the RAG from the same context as `/assistant/ask`,
 * minus the question. Follow-ups after an answer come in `AssistantAskResponse`.
 */
export type AssistantSuggestionsRequest = Omit<AssistantAskRequest, "question">;

export interface AssistantSuggestionsResponse {
  suggested_questions: string[];
}

export interface AssistantAskResponse {
  answer: string;
  /** Moments the answer is about, by `moment_id` — rendered as "jump to" buttons. */
  citations: { moment_id: string }[];
  /** Follow-ups shown under the answer. */
  suggested_questions: string[];
}

/*
 * ---------------------------------------------------------------------------
 * PROPOSED — `GET /api/v1/videos/{video_id}/tracks` (not implemented yet).
 * Object tracks to draw over the player. Source: bronze.event_objects →
 * bronze.objects → bronze.geometries, sized by bronze.videos.frame_width/height.
 * Simulated in the frontend by `./mocks/tracks.ts` until the backend ships it.
 * ---------------------------------------------------------------------------
 */

/** One bounding box at one instant, in pixels of the source frame (top-left + size). */
export interface TrackBox {
  /** `geometries.timestamp_seconds` — seconds into the video. */
  t: number;
  x: number;
  y: number;
  w: number;
  h: number;
  /** `geometries.confidence`, 0–1. */
  confidence: number | null;
}

export interface ObjectTrack {
  object_id: string;
  /** `geometries.label` / `objects.label_details` — e.g. "person", "vehicle". */
  label: string;
  /** Sorted by `t`. The frontend interpolates between boxes, so ~5–10 per second is plenty. */
  boxes: TrackBox[];
}

export interface TracksResponse {
  video_id: string;
  /** `bronze.videos.frame_width` / `frame_height` — the coordinate space of every box. */
  frame_width: number;
  frame_height: number;
  objects: ObjectTrack[];
  /** Frontend-only: true when the tracks come from the simulation, never from the backend. */
  simulated?: boolean;
}
